import { describe, it } from "bun:test";
import assert from "node:assert/strict";
import {
  categorizeFile,
  computeBreakdown,
  CATEGORY_WEIGHTS,
  detectStakes,
  routeDiff,
  EFFECTIVE_SIZE_THRESHOLD,
  MAX_LOGIC_FILES,
} from "./route-diff.ts";

describe("categorizeFile", () => {
  it("generated: @generated marker on an added line", () => {
    assert.equal(categorizeFile("pkg/foo.go", ["// @generated by tool"], [], []), "generated");
  });
  it("generated: Go DO NOT EDIT marker on a context line", () => {
    assert.equal(
      categorizeFile("pkg/foo.go", [], [], ["// Code generated by protoc. DO NOT EDIT."]),
      "generated",
    );
  });
  it("generated: protobuf filename family without marker", () => {
    assert.equal(categorizeFile("api/user.pb.go", ["something()"], [], []), "generated");
    assert.equal(categorizeFile("api/user_grpc.pb.go", ["x()"], [], []), "generated");
    assert.equal(categorizeFile("api/user.connect.go", ["x()"], [], []), "generated");
    assert.equal(categorizeFile("api/user_pb2.py", ["x()"], [], []), "generated");
  });
  it("generated: lockfiles", () => {
    for (const p of [
      "go.sum",
      "package-lock.json",
      "Cargo.lock",
      "poetry.lock",
      "jsonnetfile.lock.json",
      "deps.lock",
    ]) {
      assert.equal(categorizeFile(p, ["x"], [], []), "generated", p);
    }
  });
  it("test: hand-written test paths", () => {
    assert.equal(categorizeFile("pkg/foo_test.go", ["x()"], [], []), "test");
    assert.equal(categorizeFile("src/foo.spec.ts", ["x()"], [], []), "test");
    assert.equal(categorizeFile("src/__tests__/foo.ts", ["x()"], [], []), "test");
  });
  it("generated: snapshot and golden fixtures", () => {
    assert.equal(categorizeFile("src/__snapshots__/foo.snap", ["x"], [], []), "generated");
    assert.equal(categorizeFile("pkg/testdata/golden.txt", ["x"], [], []), "generated");
    assert.equal(categorizeFile("pkg/fixtures/output.golden", ["x"], [], []), "generated");
  });
  it("mechanical: only import lines changed", () => {
    assert.equal(
      categorizeFile(
        "src/foo.ts",
        ['import { a } from "./a.ts";'],
        ['import { a } from "../a.ts";'],
        [],
      ),
      "mechanical",
    );
  });
  it("mechanical falls through to logic when a non-import line changed", () => {
    assert.equal(
      categorizeFile("src/foo.ts", ['import { a } from "./a.ts";', "doThing();"], [], []),
      "logic",
    );
  });
  it("data-config: declarative extensions", () => {
    for (const p of [
      "config.json",
      "app.yaml",
      "app.yml",
      "Cargo.toml",
      "main.tf",
      "lib.jsonnet",
    ]) {
      assert.equal(categorizeFile(p, ["x: 1"], [], []), "data-config", p);
    }
  });
  it("logic: residual hand-written source", () => {
    assert.equal(categorizeFile("src/handler.ts", ["doThing();"], [], []), "logic");
  });
  it("precedence: a *.pb.go under a test path is generated (generated wins)", () => {
    assert.equal(categorizeFile("test/user.pb.go", ["x()"], [], []), "generated");
  });
});

describe("computeBreakdown", () => {
  it("counts changed lines per file and applies weights", () => {
    const diff = [
      "diff --git a/src/handler.ts b/src/handler.ts",
      "--- a/src/handler.ts",
      "+++ b/src/handler.ts",
      "@@ -1,1 +1,3 @@",
      " ctx();",
      "+added1();",
      "+added2();",
      "diff --git a/api/user.pb.go b/api/user.pb.go",
      "--- a/api/user.pb.go",
      "+++ b/api/user.pb.go",
      "@@ -1,1 +1,3 @@",
      "+genA()",
      "+genB()",
      "+genC()",
    ].join("\n");
    const b = computeBreakdown(diff);
    const logic = b.find((f) => f.path === "src/handler.ts");
    const gen = b.find((f) => f.path === "api/user.pb.go");
    assert.equal(logic?.category, "logic");
    assert.equal(logic?.changedLines, 2);
    assert.equal(logic?.weightedLines, 2);
    assert.equal(gen?.category, "generated");
    assert.equal(gen?.changedLines, 3);
    assert.equal(gen?.weightedLines, 0);
  });
  it("CATEGORY_WEIGHTS has the specified values", () => {
    assert.deepEqual(CATEGORY_WEIGHTS, {
      generated: 0,
      mechanical: 0,
      "data-config": 0.25,
      test: 0.5,
      logic: 1.0,
    });
  });
});

function diffFor(path: string, added: string[]): string {
  return [
    `diff --git a/${path} b/${path}`,
    `--- a/${path}`,
    `+++ b/${path}`,
    `@@ -1,1 +1,${added.length + 1} @@`,
    " ctx();",
    ...added.map((l) => `+${l}`),
  ].join("\n");
}

function diffForRemoved(path: string, removed: string[]): string {
  return [
    `diff --git a/${path} b/${path}`,
    `--- a/${path}`,
    `+++ b/${path}`,
    `@@ -1,${removed.length + 1} +1,1 @@`,
    ...removed.map((l) => `-${l}`),
    " ctx();",
  ].join("\n");
}

describe("detectStakes", () => {
  it("auth signal in a logic file", () => {
    const hits = detectStakes(diffFor("src/login.ts", ["const token = readSecret();"]));
    assert.equal(hits.length, 1);
    assert.ok(hits[0]!.reasons.includes("auth"));
  });
  it("migration signal via path and DDL", () => {
    const hits = detectStakes(
      diffFor("migrations/001_add.sql", ["ALTER TABLE users ADD COLUMN x int;"]),
    );
    assert.ok(hits[0]!.reasons.includes("migration"));
  });
  it("concurrency signal", () => {
    const hits = detectStakes(diffFor("pkg/worker.go", ["go func() { <-ch }()"]));
    assert.ok(hits[0]!.reasons.includes("concurrency"));
  });
  it("concurrency signal on a removed line", () => {
    const hits = detectStakes(diffForRemoved("src/worker.ts", ["var mu sync.Mutex"]));
    assert.equal(hits.length, 1);
    assert.ok(hits[0]!.reasons.includes("concurrency"));
  });
  it("migration DDL signal on a removed line (isolated from path signal)", () => {
    // Neutral path (not under migrations/, not *.sql) so the hit can only come
    // from the removed DDL line, not the path regex.
    const hits = detectStakes(diffForRemoved("src/schema.ts", ["DROP TABLE legacy_users;"]));
    assert.equal(hits.length, 1);
    assert.ok(hits[0]!.reasons.includes("migration"));
  });
  it("public-contract signal via .proto path", () => {
    const hits = detectStakes(diffFor("api/user.proto", ["message User { string id = 1; }"]));
    assert.ok(hits[0]!.reasons.includes("public-contract"));
  });
  it("no stakes on plain logic", () => {
    assert.deepEqual(detectStakes(diffFor("src/util.ts", ["return a + b;"])), []);
  });
  it("ignores stakes signals inside generated files", () => {
    assert.deepEqual(detectStakes(diffFor("api/user.pb.go", ["token := secret()"])), []);
  });
  it("ignores stakes signals inside test files", () => {
    assert.deepEqual(detectStakes(diffFor("src/auth.test.ts", ["const token = 'x';"])), []);
  });
  it("removed-line stakes signals do not widen eligibility to generated files", () => {
    assert.deepEqual(detectStakes(diffForRemoved("api/user.pb.go", ["var mu sync.Mutex"])), []);
  });
});

function fileDiff(path: string, addedCount: number, line = "x();"): string {
  return [
    `diff --git a/${path} b/${path}`,
    `--- a/${path}`,
    `+++ b/${path}`,
    `@@ -1,1 +1,${addedCount + 1} @@`,
    " ctx();",
    ...Array.from({ length: addedCount }, () => `+${line}`),
  ].join("\n");
}

describe("routeDiff", () => {
  it("exports tunable constants", () => {
    assert.equal(EFFECTIVE_SIZE_THRESHOLD, 150);
    assert.equal(MAX_LOGIC_FILES, 10);
  });

  it("fixture 1: 30-file protobuf regen + 10-line hand change -> quick", () => {
    const pb = Array.from({ length: 30 }, (_, i) =>
      fileDiff(`api/svc${i}.pb.go`, 80, "genLine()"),
    ).join("\n");
    const hand = fileDiff("src/handler.ts", 10, "return doThing();");
    const r = routeDiff(`${pb}\n${hand}`);
    assert.equal(r.decision, "quick");
    assert.equal(r.reason, "small");
  });

  it("fixture 2: 2-file 40-line concurrency+auth change -> full via stakes", () => {
    const a = fileDiff("pkg/worker.go", 20, "go func() { <-ch }()");
    const b = fileDiff("pkg/login.go", 20, "token := readSecret()");
    const r = routeDiff(`${a}\n${b}`);
    assert.equal(r.decision, "full");
    assert.equal(r.reason, "stakes");
    assert.ok(r.stakes.hit);
  });

  it("fixture 3: 5-file 400-line hand feature -> full via effective size", () => {
    const files = Array.from({ length: 5 }, (_, i) =>
      fileDiff(`src/feature${i}.ts`, 80, "return compute();"),
    ).join("\n");
    const r = routeDiff(files);
    assert.equal(r.decision, "full");
    assert.equal(r.reason, "effective-size");
  });

  it("fixture 4: 20-file .snap refactor -> quick", () => {
    const snaps = Array.from({ length: 20 }, (_, i) =>
      fileDiff(`src/__snapshots__/c${i}.snap`, 50, "snapshot"),
    ).join("\n");
    const r = routeDiff(snaps);
    assert.equal(r.decision, "quick");
  });
});

describe("routeDiff guards and messages", () => {
  it("logic-file-count guard: 11 tiny logic files -> full regardless of lines", () => {
    const files = Array.from({ length: 11 }, (_, i) => fileDiff(`src/m${i}.ts`, 1, "y();")).join(
      "\n",
    );
    const r = routeDiff(files);
    assert.equal(r.decision, "full");
    assert.equal(r.reason, "logic-file-count");
  });

  it("message reports the effective basis on quick", () => {
    const r = routeDiff(fileDiff("src/a.ts", 5, "return 1;"));
    assert.match(r.message, /effective/iu);
    assert.match(r.message, /--full/u);
  });
});
